# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev281+g7b82cea.d20230119'
__version_tuple__ = version_tuple = (0, 1, 'dev281', 'g7b82cea.d20230119')
